# Generated by Django 4.2.2 on 2023-06-21 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='firm',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.firm'),
        ),
    ]
