# Generated by Django 4.2.2 on 2023-06-21 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_employee_firm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firm',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.firm'),
        ),
    ]
